[core_settings]
log_level = "trace"
# The CI already timestamps the logs
log_timestamp = false
log_error_details = true

# The container runs the Parsec service as root, so make sure we disable root
# checks.
allow_root = true

[listener]
listener_type = "DomainSocket"
# The timeout needs to be smaller than the test client timeout (five seconds) as it is testing
# that the service does not hang for very big values of body or authentication length.
timeout = 3000 # in milliseconds
socket_path = "/tmp/parsec.sock"

[authenticator]
auth_type = "UnixPeerCredentials"

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"
# Warning: this path is used in the CI script
store_path = "/tmp/mappings"

[[provider]]
provider_type = "Tpm"
key_info_manager = "on-disk-manager"
tcti = "mssim"
owner_hierarchy_auth = "hex:74706d5f70617373" # "tpm_pass" in hex
